version: "3"
services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      ports:
          - "5672:5672"
      networks:
            - cm-net
  api:
    build:
      context: ./api
      dockerfile: dockerfiles/api/Dockerfile
    restart: always
    ports:
     - "5000:5000"
    links:
         - rabbit
         - redis
    depends_on:
      - redis
    networks:
      - cm-net
    volumes:
      - /var/tmp:/var/tmp
      - /var/hotmaps/repositories:/var/hotmaps/repositories
    environment:
      - ENVIRONMENT=development


  redis:
    image: redis
    networks:
          - cm-net
networks:
  cm-net:
    driver: bridge
volumes:
  static-content:



