version: "3"
services:
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      ports:
          - "5672:5672"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "80:80"
    links:
         - rabbit
         - redis
    depends_on:
      - redis
  worker:
    build:
      context: ./api
      dockerfile: Dockerfile_celery_queue
    links:
      - rabbit
    depends_on:
      - rabbit
      - redis
  monitor:
    build:
      context: ./api
      dockerfile: Dockerfile_flower
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A celery_worker.celery --port=5555 --broker=amqp://admin:mypass@rabbit:5672/
    depends_on:
      - redis
      - rabbit
  redis:
    image: redis


